print("'---'")
print("(O.O)")
print("/),,)")
print(" \" \" ")

print("     -  ")
print("    / \ ")
print("   -   -")
print("   \   /")
print("   /\'0'\\")
print("   .0.'.")
print("  .'.'0'.")
print("  0'.0'.0")
print(" '0.''0.'0.")
print("  [_____]")
print("   \___/")
